name: dtv-backend
channels:
  - conda-forge
dependencies:
  - python=3.8
  - git=2
  - pip=20
  - diskcache=5
  - click=7
  - geojson=2
  - geopandas=0.8
  - networkx>=2.4
  - numpy=1
  - pandas=1
  - pyproj=2
  - requests=2
  - scipy=1.5
  - setuptools
  - shapely=1.7
  - geos=3.8
  - tqdm
  - jupyter=1
  - notebook=6
  - jupyterlab=2
  - ipython=7
  - pip:
    - simpy
