name: dtv-backend
channels:
  - conda-forge
dependencies:
  - python=3.8
  - git
  - pip
  - DiskCache
  - click
  - geojson
  - geopandas
  - networkx>=2.4
  - numpy
  - pandas
  - pyproj
  - requests
  - scipy
  - setuptools
  - shapely
  - geos
  - tqdm
  - jupyter
  - notebook
  - jupyterlab
  - ipython
  - pip:
    - simpy
    - "--editable=git+https://github.com/TUDelft-CITG/OpenCLSim.git#egg=OpenCLSim"
    - "--editable=git+https://github.com/TUDelft-CITG/OpenTNSim.git#egg=OpenTNSim"

# - -e git@github.com:TUDelft-CITG/OpenCLSim.git#egg=OpenCLSim
# - -e git@github.com:TUDelft-CITG/OpenTNSim.git#egg=OpenTNSim
